// Builds the libraries an artifact runs against into single files agentbox can
// inject as text (see src/artifact/react-entry.js for why text).
//
// The output is committed, like frontend/dist, because a machine with no npm
// must still be able to build agentbox. `npm run build` regenerates it before vite
// runs; an unchanged result is not rewritten, so a rebuild that changes nothing
// leaves the working tree clean.

import { build } from "esbuild";
import { readFile, writeFile, mkdir } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const out = resolve(here, "../src/artifact/generated");

async function writeIfChanged(path, contents) {
  let before = null;
  try {
    before = await readFile(path, "utf8");
  } catch {
    // not there yet
  }
  if (before === contents) {
    console.log(`unchanged ${path.replace(resolve(here, ".."), ".")}`);
    return;
  }
  await writeFile(path, contents);
  console.log(`wrote ${path.replace(resolve(here, ".."), ".")} (${(contents.length / 1024).toFixed(0)} kB)`);
}

async function bundle(entry, banner) {
  const result = await build({
    entryPoints: [resolve(here, "..", entry)],
    bundle: true,
    write: false,
    format: "iife",
    minify: true,
    target: "es2022",
    // Artifacts are not a place to debug React itself, and a development build
    // costs three times the bytes in every document.
    define: { "process.env.NODE_ENV": '"production"' },
    logLevel: "warning",
  });
  return `// ${banner}\n// Generated by frontend/tools/build-runtime.mjs. Do not edit.\n${result.outputFiles[0].text}`;
}

await mkdir(out, { recursive: true });

await writeIfChanged(
  resolve(out, "react-runtime.js"),
  await bundle("src/artifact/react-entry.js", "React + ReactDOM for sandboxed artifacts."),
);

// Tailwind already ships a browser build that compiles in the page and needs no
// configuration, which is exactly the shape an injected artifact wants. Copying
// it here keeps every injected runtime in one directory with one provenance
// rule, rather than reaching into node_modules from application code.
const tailwind = await readFile(
  resolve(here, "../node_modules/@tailwindcss/browser/dist/index.global.js"),
  "utf8",
);
await writeIfChanged(
  resolve(out, "tailwind-runtime.js"),
  `// Tailwind CSS browser build, copied from @tailwindcss/browser.\n// Generated by frontend/tools/build-runtime.mjs. Do not edit.\n${tailwind}`,
);
