// drawhtml renders the wiki frames' documents with the product's own renderer.
//
// Three of the drawn frames (FR99) show rendered markdown rather than a surface
// full of fields: the reading window, the artifact, and the console's turn with
// a table and a code block in it. In the product that HTML comes from Go -
// internal/webui/mdhtml.go decides the headings, the tables, the highlighted
// code and the alerts, and internal/webui/artifact.go decides an artifact's
// chrome and its sandbox. A fixture that hand-wrote that HTML would be drawing
// a renderer nobody ships, which is exactly the failure FR99's honesty rule is
// about: a frame may say nothing a real run would contradict.
//
// So the fixtures hold markdown, and this turns it into the same HTML a real
// document would carry. draw.py runs it before serving, so the two cannot drift:
// change mdhtml.go and the next drawing shows it.
//
//	go run ./tools/wiki/drawhtml
//
// Sources are frontend/draw/md/*.md, keyed by the name before the first dot. A
// file named *.artifact.* goes through RenderArtifact instead, which is the
// viewer's path for `agentbox artifact`, and takes its title and id from a
// first-line marker:
//
//	<!-- agentbox: title=How much traffic should the new build take? id=art-canary -->
//
// The output, frontend/draw/rendered.js, is committed: drawing needs npm and
// chrome already, and asking it to need a Go toolchain as well would make a
// frame harder to redraw than to photograph.
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/borismilner/agentbox/internal/webui"
)

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "drawhtml:", err)
		os.Exit(1)
	}
}

func run() error {
	root, err := repoRoot()
	if err != nil {
		return err
	}
	src := filepath.Join(root, "frontend", "draw", "md")
	entries, err := os.ReadDir(src)
	if err != nil {
		return err
	}

	var names []string
	for _, e := range entries {
		if !e.IsDir() && (strings.HasSuffix(e.Name(), ".md") || strings.Contains(e.Name(), ".artifact.")) {
			names = append(names, e.Name())
		}
	}
	sort.Strings(names)

	var b strings.Builder
	b.WriteString("// Generated by tools/wiki/drawhtml - do not edit.\n")
	b.WriteString("//\n")
	b.WriteString("// The HTML a drawn frame's document is made of, rendered by the product's own\n")
	b.WriteString("// renderer from the markdown in frontend/draw/md/. Regenerate with\n")
	b.WriteString("// `go run ./tools/wiki/drawhtml`; draw.py does it for you before it serves.\n")
	b.WriteString("\nexport const HTML = {\n")

	for _, name := range names {
		raw, err := os.ReadFile(filepath.Join(src, name))
		if err != nil {
			return err
		}
		text := string(raw)
		key, _, _ := strings.Cut(name, ".")

		var html string
		if strings.Contains(name, ".artifact.") {
			title, id, body := marker(text)
			html = webui.RenderArtifact(body, title, id)
		} else {
			html = webui.RenderMarkdown(text)
		}
		fmt.Fprintf(&b, "  %q: %s,\n", key, quote(html))
	}
	b.WriteString("};\n")

	out := filepath.Join(root, "frontend", "draw", "rendered.js")
	if err := os.WriteFile(out, []byte(b.String()), 0o644); err != nil {
		return err
	}
	fmt.Printf("drawhtml: %d document(s) -> %s\n", len(names), out)
	return nil
}

// marker reads the first-line title/id declaration off an artifact source and
// returns the source without it. Both are what the viewer would have been given
// by the caller, and the id is what an event from the artifact is stamped with.
func marker(text string) (title, id, body string) {
	line, rest, found := strings.Cut(text, "\n")
	if !found || !strings.HasPrefix(strings.TrimSpace(line), "<!-- agentbox:") {
		return "", "", text
	}
	fields := strings.TrimSuffix(strings.TrimPrefix(strings.TrimSpace(line), "<!-- agentbox:"), "-->")
	// title runs to the end of the field list, so it is read last and keeps its
	// spaces; id is one token.
	if i := strings.Index(fields, "id="); i >= 0 {
		id = strings.Fields(fields[i+len("id="):])[0]
		fields = fields[:i]
	}
	if _, after, ok := strings.Cut(fields, "title="); ok {
		title = strings.TrimSpace(after)
	}
	return title, id, rest
}

// quote writes a JS string literal. A Go %q is not one: it escapes non-ASCII as
// \x.. bytes that JavaScript reads as Latin-1, and the rendered HTML is full of
// the typographic characters goldmark produces.
func quote(s string) string {
	var b strings.Builder
	b.WriteByte('"')
	for _, r := range s {
		switch r {
		case '"':
			b.WriteString(`\"`)
		case '\\':
			b.WriteString(`\\`)
		case '\n':
			b.WriteString(`\n`)
		case '\r':
			b.WriteString(`\r`)
		case '\t':
			b.WriteString(`\t`)
		case '\u2028':
			b.WriteString(`\u2028`)
		case '\u2029':
			b.WriteString(`\u2029`)
		default:
			b.WriteRune(r)
		}
	}
	b.WriteByte('"')
	return b.String()
}

func repoRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("no go.mod above %s", dir)
		}
		dir = parent
	}
}
